TypeCobolStudio/TypeCobolStudio.csproj
TypeCobolStudio/packages.config

A reference was missing in order to build the solution

Add Antlr4.Runtime reference and update NuGet configuration

---

TypeCobol.Grammar/Grammars/Cobol/CobolCodeElements.g4
TypeCobol.Test/Compiler/Parser/ResultFiles/PERFORMCodeElements.txt
TypeCobol.Test/TestCollection.cs

This was broken after the last merges between osmedile and me.
Now it isn't anymore.

Uncomment PERFORM statement test

---

TypeCobol.Grammar/Grammars/Cobol/CobolCodeElements.g4
TypeCobol/Compiler/CodeElements/Statement/StartStatement.cs
TypeCobol/Compiler/CodeElements/Statement/StopStatement.cs
TypeCobol/Compiler/CodeElements/Statement/StringStatement.cs
TypeCobol/Compiler/CodeElements/Statement/UnstringStatement.cs
TypeCobol/Compiler/CodeElements/Statement/WriteStatement.cs
TypeCobol/Compiler/CodeElements/Statement/XmlGenerateStatement.cs
TypeCobol/Compiler/CodeElements/Statement/XmlParseStatement.cs
TypeCobol/Compiler/Diagnostics/Cobol85Checkers.cs
TypeCobol/Compiler/Parser/CodeElementBuilder/CobolCodeElementBuilder.cs
TypeCobol/Compiler/Parser/CodeElementBuilder/CobolExpressionsBuilder.cs
TypeCobol/Compiler/Parser/CodeElementBuilder/CobolStatementsBuilder.cs

End of grammar refactoring for the following code elements : StringStatement, SubtractStatement, UnstringStatement, WriteStatement, XmlGenerateStatement, XmlParseStatement

End of CodeElements grammar refactoring

---

TypeCobol.Test/Compiler/Parser/ResultFiles/Programs/Cobol2002/TypedefPGM.txt
TypeCobol.Test/Compiler/Parser/Samples/Programs/Cobol2002/Typedef.tcbl
TypeCobol.Test/NewTestsToFix/Parser/ResultFiles/HighPriority/MissingSentenceEndPGM.txt
TypeCobol.Test/NewTestsToFix/Parser/ResultFiles/HighPriority/Type-GlobalPGM.txt
TypeCobol.Test/NewTestsToFix/Parser/ResultFiles/HighPriority/Type-TCTYPE_LIMITED_STRONG_RECEIVERPGM.txt
TypeCobol.Test/NewTestsToFix/Parser/Samples/HighPriority/MissingSentenceEnd.tcbl
TypeCobol.Test/NewTestsToFix/Parser/Samples/HighPriority/Type-Global.tcbl
TypeCobol.Test/NewTestsToFix/Parser/Samples/HighPriority/Type-TCTYPE_LIMITED_STRONG_RECEIVER.tcbl
TypeCobol.Test/TypeCobol.Test.csproj
TypeCobol/Compiler/Parser/NodeBuilder/CobolNodeBuilder.cs

Tests for Type and Typedef

---

CLI/test/ressources/dependencies_1/output_expected/ProcedureCall-Public.rdz.tcbl
CLI/test/ressources/dependencies_2/output_expected/PGM2.rdz.tcbl
CLI/test/ressources/generate_1/output_expected/FunDeclare.rdz.tcbl
CLI/test/ressources/return_code_0/output_expected/FunDeclare.rdz.tcbl
Codegen/test/resources/output/TypeCobol/Codegen.rdz.cbl
Codegen/test/resources/output/TypeCobol/FUNCTION.rdz.cbl
Codegen/test/resources/output/TypeCobol/FunDeclare.rdz.cbl
Codegen/test/resources/output/TypeCobol/Library.rdz.cbl
Codegen/test/resources/output/TypeCobol/Library2.rdz.tcbl
Codegen/test/resources/output/TypeCobol/Library3.rdz.tcbl
Codegen/test/resources/output/TypeCobol/Library4.rdz.tcbl
Codegen/test/resources/output/TypeCobol/ProcedureCall-PrivateQualifier.rdz.tcbl
Codegen/test/resources/output/TypeCobol/ProcedureCall-Public.rdz.tcbl
Codegen/test/resources/output/TypeCobol/ProcedureCall-Public2.rdz.tcbl
Codegen/test/resources/output/TypeCobol/ProcedureCall-Public3.rdz.tcbl
Codegen/test/resources/output/TypeCobol/ProcedureCall.rdz.cbl
TypeCobol.Test/Hash.cs
TypeCobol/Compiler/Nodes/Node.cs
TypeCobol/Compiler/Nodes/Procedure.cs
TypeCobol/Tools/Hash.cs

Issue #464, add hash dictionary in Root node

---

TypeCobol.LanguageServer/Completion Factory/CompletionFactoryHelpers.cs
TypeCobol.LanguageServer/VsCodeProtocol/Completion Support/CompletionItemKind.cs

The Client now support Intrinsic Type Icon

#759, add custom Kind for intrinsic type.

---

TypeCobol.Test/Parser/Programs/TypeCobol/LibraryFunctionDeclarativeCheck.rdz.tcbl
TypeCobol.Test/Parser/Programs/TypeCobol/LibraryFunctionDeclarativeCheck.rdzPGM.txt
TypeCobol.Test/Parser/Programs/TypeCobol/SubstractCorrNullReferenceException.rdz.tcbl
TypeCobol.Test/Parser/Programs/TypeCobol/SubstractCorrNullReferenceException.rdz.txt
TypeCobol.Test/TypeCobol.Test.csproj
TypeCobol/Compiler/CodeElements/Statement/SubstractStatement.cs
TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs

#863 adding test files and clarifying error message

---

TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureCall-public.rdz-Nodes.txt
TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureCall-public.rdz.tcbl
TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureCall-public.rdzPGM.txt

Code is OK. Added test case to highlight error message.

Issue #930 - Updated test case for undefined variable

---

CLI/test/ressources/outputSignature_1/input/Callee.rdz.tcbl
Codegen/src/Generators/SignaturesGenerator.cs

Added override for Visit(LinkageSection).
Updated test file.

Fix #784 public signature export

---

CLI/src/config/skeletons.xml
CLI/test/ressources/dependencies_1/output_expected/ProcedureCall-Public.rdz.tcbl
CLI/test/ressources/dependencies_2/output_expected/PGM2.rdz.tcbl
Codegen/src/Nodes/FunctionDeclarationCG.cs
Codegen/test/resources/output/TypeCobol/CallPublicProcFromPrivateProc.rdz.tcbl
Codegen/test/resources/output/TypeCobol/ProcedureCall-Public.rdz.tcbl
Codegen/test/resources/output/TypeCobol/ProcedureCall-Public2.rdz.tcbl
Codegen/test/resources/output/TypeCobol/ProcedureCall-Public3.rdz.tcbl
Codegen/test/resources/output/TypeCobol/ProcedureCall-PublicAndDeclaratives.rdz.tcbl
Codegen/test/resources/output/TypeCobol/ProcedureCall-PublicAndDeclaratives2.rdz.tcbl
Codegen/test/resources/output/TypeCobol/ProcedureCall-PublicAndDeclaratives3.rdz.tcbl
Codegen/test/resources/output/TypeCobol/ProcedureCall-PublicAndDeclaratives4.rdz.tcbl

Issue #886 updated pattern for working storage program definition

---

TypeCobol/Compiler/CodeModel/SymbolTable.cs
TypeCobol/Compiler/Diagnostics/CrossChecker.cs
TypeCobol/Compiler/Nodes/Node.cs

OrdinalIgnoreCase for StringComparison

Issue #1021 Changed culture from InvariantCultureIgnoreCase to

---

TypeCobol/Compiler/Diagnostics/CrossChecker.cs
TypeCobol/Compiler/Nodes/Node.cs

Updated Visit(Move move) overriden method

Issue #996 - Removed unused code in CheckVariable

---

TypeCobol/Compiler/Diagnostics/Cobol2002Checker.cs
TypeCobol/Compiler/Diagnostics/CrossChecker.cs
TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs
TypeCobol/Compiler/Parser/CodeElementDispatcher.cs

and RedefinesChecker classes
Override Visit() methods.
Refactor OnNode method for direct call from Visit()

WI #1027 Removed reflexion for calls to FunctionDeclarationChecker

---

Codegen/src/Nodes/FunctionDeclarationCG.cs
Codegen/src/Nodes/ParameterEntry.cs
Codegen/test/resources/input/TypeCobol/Pointers.rdz.tcbl
Codegen/test/resources/output/TypeCobol/Pointers.rdz.tcbl
TypeCobol/Compiler/CupParser/NodeBuilder/ProgramClassBuilder.cs
TypeCobol/Compiler/Nodes/Node.cs

Add redefines generation for pointer inside function + Unit Test

Issue  #1071: redefines generation inside function

---

TypeCobol/Compiler/Nodes/Data.cs
TypeCobol/Compiler/Text/ReadOnlyTextLine.cs
TypeCobol/TypeCobol.ruleset

3 properties were hiding parent properties but were in fact the exact same code.

Issue #951, Activate more compilation rules

---

Codegen/test/resources/input/TypeCobol/BooleanTester.rdz.tcbl
Codegen/test/resources/output/TypeCobol/BooleanTester.rdz.tcbl
TypeCobol.Test/Parser/Programs/TypeCobol/CallWithPointerOverload.rdz.tcbl
TypeCobol.Test/Parser/Programs/TypeCobol/CallWithPointerOverload.rdzMix.txt
TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureCall-AddressOf.rdz.tcbl
TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureCall-AddressOf.rdzPGM.txt
TypeCobol/Compiler/CodeElements/Expressions/StorageArea.cs
TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs

Needs to merge this one before merging issue 978 to develop

Issue #1068, CALL with pointer and procedure overload

---

TypeCobol/Compiler/CodeElements/Expressions/StorageArea.cs

Technically, tally is in a ALL variable, still real fix to implement

WI #1120, temporary fix to display tally

---

Codegen/src/Actions/Qualifier.cs
TypeCobol.Test/Parser/Programs/Cobol2002/DependingOn2002.rdz.tcbl
TypeCobol.Test/Parser/Programs/Cobol2002/DependingOn2002.rdzMix.txt
TypeCobol/Compiler/CodeModel/SymbolTable.cs
TypeCobol/Compiler/Diagnostics/Cobol2002Checker.cs
TypeCobol/Compiler/Diagnostics/CrossChecker.cs
TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs
TypeCobol/Compiler/Nodes/Attributes.cs
TypeCobol/Compiler/Nodes/Data.cs
TypeCobol/Compiler/Nodes/Node.cs
TypeCobol/Compiler/Nodes/Procedure.cs

WI #1301 #1294
Second part of optimization on SymbolTable.
Focus is done on VisualQualifiedName.
This property is costly and in most situations we don't need it.
You can look at each commit message to get more details.
Performance gain are only visible for deep variables declaration.
The gain is very small for Part1_Incremental tests because variable declaration are not deep enough.
|                                                       |                     | 
|-------------------------------------------------------|---------------------| 
| **Test**                                                  | **Gain** | 
| Part1_FullParsing_Cobol85_NoRedefines                 |                     | 
| Part1_FullParsing_TC_BigTypesNoProcedure              |                     | 
| …

WI #1301 #1294 optimize symbol table part2

---

TypeCobol.Test/TypeCobol.Test.csproj
TypeCobol.Test/packages.config
appveyor.yml

- Added cache to config file appveyor.yml
- Removed all unused Rx-* packages from Test in NuGet

WI #1203 AppVeyor: Keep nuget cache between builds

---

TypeCobol.LanguageServer.Test/LSRTest.cs
TypeCobol.LanguageServer.Test/LSRTestHelper.cs
TypeCobol.LanguageServer.Test/LSRTests/OutlineRefresh/input/OutlineRefresh.tlsp
TypeCobol.LanguageServer.Test/LSRTests/OutlineRefresh/output_expected/OutlineRefresh.rlsp
TypeCobol.LanguageServer.Test/TypeCobol.LanguageServer.Test.csproj
TypeCobol.LanguageServer/Interfaces/ILanguageServer.cs
TypeCobol.LanguageServer/TypeCobol.LanguageServer.csproj
TypeCobol.LanguageServer/TypeCobolCustomLanguageServer/Refresh Outline Notification/OutlineNode.cs
TypeCobol.LanguageServer/TypeCobolCustomLanguageServer/Refresh Outline Notification/RefreshOutlineNotification.cs
TypeCobol.LanguageServer/TypeCobolCustomLanguageServer/Refresh Outline Notification/RefreshOutlineParams.cs
TypeCobol.LanguageServer/TypeCobolCustomLanguageServer/TypeCobolCustomLanguageServer.cs
TypeCobol.LanguageServer/TypeCobolLanguageServer.cs
TypeCobol.LanguageServer/TypeCobolServer.cs
TypeCobol.LanguageServer/TypeCobolServerHost.cs
TypeCobol.LanguageServer/Workspace.cs
TypeCobol/Compiler/Diagnostics/CrossChecker.cs

1031 outline rebase final

---

CLI/test/CLITest.cs
CLI/test/ressources/value_clauses/CLIArguments.txt
CLI/test/ressources/value_clauses/input/Intrinsic.txt
CLI/test/ressources/value_clauses/input/ValueClauses.rdz.tcbl
CLI/test/ressources/value_clauses/output_expected/ValueClauses.rdz.tcbl
CLI/test/ressources/value_clauses/output_expected/error.txt
Codegen/src/Nodes/ParameterEntry.cs
Codegen/src/Nodes/TypedDataNode.cs

791 preserve value clause in proc params and typed variables rebase

---

TypeCobol.LanguageServer/Workspace.cs
TypeCobol/Compiler/File/LocalDirectoryLibrary.cs

Issue #1442
Original PRs #1504 and #1462 have been approved so no need to review this one.

Rebase of PR #1504

---

TypeCobol.Test/Parser/CodeElements/ALTER.txt
TypeCobol.Test/Parser/Programs/Cobol85/AlterWarning.cbl
TypeCobol.Test/Parser/Programs/Cobol85/AlterWarningPGM.Txt
TypeCobol/Compiler/Diagnostics/CodeElementCheckers.cs
TypeCobol/Compiler/Parser/CodeElementBuilder/CobolCodeElementBuilder.cs
TypeCobol/Compiler/Parser/CodeElementBuilder/CobolStatementsBuilder.cs
TypeCobol/Compiler/Parser/DiagnosticUtils.cs

It's a rebase version: PR is #1471

WI #1453 Add Diagnostic when using ALTER

---

Codegen/src/Generator.cs
Codegen/src/Generators/DefaultGenerator.cs
Codegen/src/Generators/DefaultGeneratorWithLineMap.cs
Codegen/src/Generators/DocumentationGenerator.cs
Codegen/src/Generators/ExpandingCopyGenerator.cs
Codegen/src/Generators/SignaturesGenerator.cs
Codegen/src/IGenerator.cs
Codegen/test/Performance.cs

Rebased version of #1507 which has already been reviewed and approved.

791 add performance data in codegen rebase 2

---

Codegen/src/Nodes/TypedDataNode.cs
Codegen/test/TestTypeCobolCodegen.cs
Codegen/test/resources/input/TypeCobol/ProcedureScalarTypedef.rdz.tcbl
Codegen/test/resources/input/TypeCobol/TypedefComments.rdz.tcbl
Codegen/test/resources/output/TypeCobol/ProcedureScalarTypedef.rdz.tcbl
Codegen/test/resources/output/TypeCobol/TypedefComments.rdz.tcbl

Fix for issues #1538 et #1540.

1538 1540 comments in typedef with codegen

---

TypeCobol.LanguageServer.Test/LSRTest.cs
TypeCobol.LanguageServer.Test/LSRTests/CompletionAfterBetweenColons/input/CompletionAfterBetweenColons.tlsp
TypeCobol.LanguageServer.Test/LSRTests/CompletionAfterBetweenColons/output_expected/CompletionAfterBetweenColons.rlsp
TypeCobol.LanguageServer.Test/TypeCobol.LanguageServer.Test.csproj
TypeCobol.LanguageServer/Completion Factory/CompletionFactory.cs

Fix for issues #1428 and #1484.

WI #1428 #1484 Avoid exception when completing after or between colon

---

TypeCobol.LanguageServer/Completion Factory/CompletionFactory.cs
TypeCobol.LanguageServer/TypeCobolServer.cs
TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs
TypeCobol/Compiler/Nodes/Node.cs

see issues https://github.com/TypeCobolTeam/TypeCobol/issues/1579 and https://github.com/TypeCobolTeam/TypeCobol/issues/1590

WI #1579 #1590 Fix hover and completion exceptions

---

TypeCobol/Compiler/Domain/ProgramSymbolTableBuilder.cs
TypeCobol/Compiler/Domain/SymbolTableBuilder.cs
TypeCobol/Compiler/Scopes/Scope.cs
TypeCobol/Compiler/Symbols/AbstractScope.cs
TypeCobol/Compiler/Symbols/VariableSymbol.cs
TypeCobol/Compiler/Symbols/VariableTypeSymbol.cs

Small changes for 1260_DataflowDomain

1260 dataflow domain smedilol 1

---

TypeCobol/Compiler/CupParser/NodeBuilder/ProgramClassBuilder.cs
TypeCobol/Compiler/CupParser/NodeBuilder/ProgramClassBuilderNodeDispatcher.cs
TypeCobol/Compiler/CupParser/NodeBuilder/ProgramClassBuilderNodeListener.cs
TypeCobol/Compiler/Parser/CodeElementDispatcher.cs
TypeCobol/Compiler/Parser/ProgramClassParserStep.cs

Close #1263
I've extracted the commits from branch 1260_DataflowDomain and I fixed conflicts with develop.
I propose to merge this apart from PR #1309

Close #1263 Add Listener/Dispatcher interfaces fornode creation/parsing action

---

TypeCobol.Test/Parser/Programs/TypeCobol/GlobalStorageSection.rdz.tcbl
TypeCobol.Test/Parser/Programs/TypeCobol/GlobalStorageSection.rdzMix.txt
TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs

1629 global storage only in main program

---

TypeCobol.Test/Parser/Programs/TypeCobol/GlobalStorageVisibility.rdz.tcbl
TypeCobol.Test/Parser/Programs/TypeCobol/GlobalStorageVisibility.rdzMix.txt
TypeCobol.Test/Parser/Programs/TypeCobol/Typedef-public.rdz.tcbl

Anticipating new unit test from PR #1309.

WI #1260 Add unit test for GlobalStorage visibility

---

Codegen/test/resources/input/TypeCobol/TypedefComments.rdz.tcbl
Codegen/test/resources/output/TypeCobol/TypedefComments.rdz.tcbl
TypeCobol.Test/Parser/Programs/Cobol85/ValueClauseArea.rdz.cbl
TypeCobol.Test/Parser/Programs/Cobol85/ValueClauseArea.rdzMix.txt
TypeCobol/Compiler/Diagnostics/CodeElementCheckers.cs
TypeCobol/Compiler/DocumentFormat.cs
TypeCobol/Compiler/Text/TextArea.cs

Update develop with latest v1.4.1

Merge v1.4.1 in develop 20200206

---

TypeCobol.Test/Parser/Programs/Cobol85/WarningEndAlignment.rdz.cbl
TypeCobol.Test/Parser/Programs/Cobol85/WarningEndAlignment.rdzPGM.txt
TypeCobol/Compiler/Diagnostics/CrossChecker.cs

Weekly update of develop branch with 1.4.1

Merge 1.4.1 into develop 20200309

---

Codegen/src/Generators/LinearNodeSourceCodeMapper.cs
TypeCobol.Test/GrammarTest.cs

Temporary fix for EITests because of bugs that should be adressed in #1704.

1704 disable codegen on ei tests

---

Codegen/src/Nodes/TypedDataNode.cs
Codegen/test/TestTypeCobolCodegen.cs
Codegen/test/resources/input/TypeCobol/Global_Storage/GlobalStorageWithTypedefAndIndex.rdz.tcbl
Codegen/test/resources/output/TypeCobol/Global_Storage/GlobalStorageWithTypedefAndIndex.rdz.tcbl

WI #1703 Fix index hashes map generation

---

Codegen/src/Nodes/TypedDataNode.cs
Codegen/test/TestTypeCobolCodegen.cs
Codegen/test/resources/input/TypeCobol/Global_Storage/GlobalStorageWithTypedefAndIndex.rdz.tcbl
Codegen/test/resources/output/TypeCobol/Global_Storage/GlobalStorageWithTypedefAndIndex.rdz.tcbl

This release only contains fix to issue #1703 : wrong function hash generated when variable declared in global-storage section.

v1.4.2 release

---

TypeCobol.Test/Parser/Programs/Cobol85/CPYData3.cpy
TypeCobol.Test/Parser/Programs/Cobol85/CPYData4.cpy
TypeCobol.Test/Parser/Programs/Cobol85/DataGroupEmpty.cbl
TypeCobol.Test/Parser/Programs/Cobol85/DataGroupEmpty.txt
TypeCobol.Test/Parser/Programs/Cobol85/DataGroupEmptyPGM.txt
TypeCobol/Compiler/Diagnostics/CrossChecker.cs

(cherry picked from commit 502486614f62fa407dd30dbfd7c237274cc96e77)
Fixes #1637

WI 1637 Check copy level number following empty group item

---

Codegen/src/Nodes/FunctionDeclarationCG.cs
Codegen/test/TestTypeCobolCodegen.cs
Codegen/test/resources/input/TypeCobol/DeclarativesInsideProcedure.rdz.tcbl
Codegen/test/resources/output/TypeCobol/DeclarativesInsideProcedure.rdz.tcbl

WI #1713 Perform TC-INITIALIZATIONS after declaratives if any

---

TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureInput.rdz.tcbl
TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureInput.rdzMix.txt
TypeCobol/Compiler/Diagnostics/CrossChecker.cs

WI 1625 Address change on input parameter

---

Codegen/src/Nodes/FunctionDeclarationCG.cs
Codegen/test/TestTypeCobolCodegen.cs
Codegen/test/resources/input/TypeCobol/DeclarativesInsideProcedure.rdz.tcbl
Codegen/test/resources/output/TypeCobol/DeclarativesInsideProcedure.rdz.tcbl
TypeCobol.Test/Parser/Programs/Cobol85/CPYData3.cpy
TypeCobol.Test/Parser/Programs/Cobol85/CPYData4.cpy
TypeCobol.Test/Parser/Programs/Cobol85/DataGroupEmpty.cbl
TypeCobol.Test/Parser/Programs/Cobol85/DataGroupEmpty.txt
TypeCobol.Test/Parser/Programs/Cobol85/DataGroupEmptyPGM.txt
TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureInput.rdz.tcbl
TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureInput.rdzMix.txt
TypeCobol/Compiler/Diagnostics/CrossChecker.cs

Periodic merge of v1.4.3 into develop.

Merge 1.4.3 into develop 20200525

---

TypeCobol.Test/Parser/Programs/TypeCobol/Typedef-strict.rdz.tcbl
TypeCobol.Test/Parser/Programs/TypeCobol/Typedef-strict.rdzPGM-EI.txt
TypeCobol.Test/Parser/Programs/TypeCobol/Typedef-strict.rdzPGM.txt
TypeCobol/Compiler/CodeElements/Entry/DataType.cs
TypeCobol/Compiler/Diagnostics/Cobol2002Checker.cs
TypeCobol/Compiler/Diagnostics/CrossChecker.cs
TypeCobol/Compiler/Domain/ProgramSymbolTableBuilder.cs
TypeCobol/Compiler/Symbols/Builtins.cs

Rebase of PR #1729.
Closes #960

WI 960 ForbidSyncClauseWithStrictType

---

TypeCobol.Test/Parser/Programs/Cobol85/ParagraphSection.rdz.cbl
TypeCobol.Test/Parser/Programs/Cobol85/ParagraphSection.rdzPGM.txt
TypeCobol.Test/Parser/Programs/TypeCobol/ParagraphsSectionsPGM.txt
TypeCobol.Test/Parser/Programs/TypeCobol/ParagraphsSectionsSYM.txt
TypeCobol.Test/TestUtils.cs
TypeCobol/Compiler/CodeModel/SymbolTable.cs
TypeCobol/Compiler/Diagnostics/CrossChecker.cs
TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs

WI 1710 Check duplicate paragraph names with semantic data owner

---

Codegen/src/Nodes/ProcedureStyleCall.cs
Codegen/test/resources/input/TypeCobol/Global_Storage/GlobalStorageWithTypedefAndIndex.rdz.tcbl
Codegen/test/resources/output/TypeCobol/Global_Storage/GlobalStorageWithTypedefAndIndex.rdz.tcbl
TypeCobol/Compiler/CodeElements/Expressions/StorageArea.cs
TypeCobol/Compiler/Nodes/Node.cs
TypeCobol/Tools/Hash.cs

Merge v1.4.3 into develop 20200929

---

Codegen/src/Nodes/ProcedureStyleCall.cs
Codegen/test/resources/input/TypeCobol/Global_Storage/GlobalStorageWithTypedefAndIndex.rdz.tcbl
Codegen/test/resources/output/TypeCobol/Global_Storage/GlobalStorageWithTypedefAndIndex.rdz.tcbl
TypeCobol/Compiler/CodeElements/Expressions/StorageArea.cs
TypeCobol/Compiler/Nodes/Node.cs
TypeCobol/Tools/Hash.cs

Remember index hash on StorageArea and use it during code generation (PR #1764)

WI #1762 Fix index hash in CALL arguments

---

TypeCobol.Test/Parser/Preprocessor/ReplaceResultFiles/PgmReplacePartial.txt
TypeCobol.Test/Parser/Preprocessor/ReplaceTestFiles/PgmReplacePartial.cbl
TypeCobol/Compiler/Preprocessor/ReplaceTokensLinesIterator.cs

WI #1780 Replace all placeholders in partial word replace operations

---

TypeCobol/Common.props

WI #1800 Disable CodeAnalysis for Debug-like configurations

---

CLI/test/CLITest.cs
CLI/test/ressources/dependenciesNotLoadedInCorrectOrder/output_expected/error.txt
CLI/test/ressources/dependenciesSignatureOverload_2/CLIArguments.txt
CLI/test/ressources/dependenciesSignatureOverload_2/input/Dependency.tcbl
CLI/test/ressources/dependenciesSignatureOverload_2/input/Main.tcbl
CLI/test/ressources/dependenciesSignatureOverload_2/output_expected/errors.txt
TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureCall.rdzPGM.txt
TypeCobol/Compiler/CodeElements/Entry/DataType.cs
TypeCobol/Compiler/CupParser/NodeBuilder/ProgramClassBuilder.cs
TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs

WI #1786 #1796 Fix argument type comparison in TypeCobolChecker

---

CLI/src/CLI.cs
CLI/test/CLITest.cs
CLI/test/ressources/custom_analyzers/CLIArguments.txt
CLI/test/ressources/custom_analyzers/input/CustomAnalyzers.rdz.tcbl
CLI/test/ressources/custom_analyzers/output_expected/errors.txt
TypeCobol.Analysis.Test/CustomAnalyzers/Analyzers.cs
TypeCobol.Analysis.Test/CustomAnalyzers/TestAnalyzerProvider.cs
TypeCobol.Analysis.Test/TypeCobol.Analysis.Test.csproj
TypeCobol.LanguageServer/Workspace.cs
TypeCobol/Analysis/AnalyzerProvider.cs
TypeCobol/Analysis/AnalyzerProviderLoader.cs
TypeCobol/Tools/Options-Config/TypeCobolConfiguration.cs

Fixes #1825.
No error handling yet but it works...

WI #1825 Find and load analyzers from external assemblies

---

TypeCobol/AntlrGrammar/CobolExpressions.g4
TypeCobol/Compiler/Parser/CodeElementBuilder/CobolExpressionsBuilder.cs

This is a small change in the grammar to allow all special register in subscripts and not only TALLY.

WI #1120 Allow special registers in subscripts

---

CLI/test/CLITest.cs
CLI/test/ressources/checkMissingCopies_2/CLIArguments.txt
CLI/test/ressources/checkMissingCopies_2/input/Copies/COPY1.CPY
CLI/test/ressources/checkMissingCopies_2/input/Copies/COPY2.CPY
CLI/test/ressources/checkMissingCopies_2/input/MissingCopy.rdz.tcbl
CLI/test/ressources/checkMissingCopies_2/output_expected/MissingCopy.txt
CLI/test/ressources/checkMissingCopies_2/output_expected/error.txt
TypeCobol.LanguageServer/Workspace.cs
TypeCobol.Test/Parser/Preprocessor/CopyResultFiles/PgmCopy.txt
TypeCobol/Analysis/Violation.cs
TypeCobol/Compiler/CompilationDocument.cs
TypeCobol/Compiler/Diagnostics/Diagnostic.cs
TypeCobol/Compiler/Diagnostics/DiagnosticMessage.cs
TypeCobol/Compiler/Diagnostics/MessageCode.cs
TypeCobol/Compiler/Diagnostics/Resources/DiagnosticMessages.csv
TypeCobol/Compiler/Preprocessor/MissingCopy.cs
TypeCobol/Compiler/Preprocessor/PreprocessorStep.cs
TypeCobol/Compiler/Preprocessor/ProcessedTokensDocument.cs
TypeCobol/Parser.cs
TypeCobol/Tools/APIHelpers/Helpers.cs

Fixes #1808.
Rebase version of #1815.

1808 report missing copies all levels ptd rebase

---

Analytics/packages.config
CLI/test/CLI.Test.csproj
CSCup/App.config
Codegen/src/App.config
Codegen/src/Codegen.csproj
Codegen/src/packages.config
Codegen/test/Codegen.Test.csproj
TypeCobol.Analysis/packages.config
TypeCobol.LanguageServer.Test/TypeCobol.LanguageServer.Test.csproj
TypeCobol.LanguageServer.Test/packages.config
TypeCobol.LanguageServer/App.config
TypeCobol.LanguageServer/packages.config
TypeCobol.Test/TypeCobol.Test.csproj
TypeCobol.Test/packages.config
TypeCobol.Transform.Test/TypeCobol.Transform.Test.csproj
TypeCobol.Transform/App.config
TypeCobol/Common.props
TypeCobol/packages.config

This reverts commit b4489ba116aaada73b47350572833ca8a98f0b67.

Revert "WI #1834 Target .NET framework 4.7.2 (#1850)"

---

CLI/src/CLI.cs
CLI/src/Writer.cs
CLI/test/CLITest.cs
CLI/test/ressources/mass_generation_xmldiagformat/CLIArguments.txt
CLI/test/ressources/mass_generation_xmldiagformat/input/DVZZPGM1.tcbl
CLI/test/ressources/mass_generation_xmldiagformat/input/DVZZPGM2.tcbl
CLI/test/ressources/mass_generation_xmldiagformat/input/DVZZPGM3.tcbl
CLI/test/ressources/mass_generation_xmldiagformat/output_expected/DVZZPGM3.cbl
CLI/test/ressources/mass_generation_xmldiagformat/output_expected/error.xmldiag
TypeCobol/Tools/Options-Config/TypeCobolConfiguration.cs

WI #1845 Add .xmldiag format for error output in CLI

---

TypeCobol.Analysis.Test/PerformanceWithCfg.cs
TypeCobol.Analysis.Test/PerformanceWithCfgDfa.cs
TypeCobol.Analysis.Test/TypeCobol.Analysis.Test.csproj
TypeCobol.Test/Parser/Performance/Performance.cs

**What have been done:**
Add two classes in TypeCobol.Analysis.Test
- PerformanceWithCfg
- PerformanceWithCfgDfa
Both inherit from class TypeCobol.Test.Performance

WI #1864 Add peformance test with CFG/DFA

---

CLI/test/CLITest.cs
CLI/test/ressources/dependenciesSignatureOverload_4/CLIArguments.txt
CLI/test/ressources/dependenciesSignatureOverload_4/input/Dependency.tcbl
CLI/test/ressources/dependenciesSignatureOverload_4/input/Main.tcbl
CLI/test/ressources/dependenciesSignatureOverload_4/output_expected/Main.cbl
CLI/test/ressources/dependenciesSignatureOverload_4/output_expected/errors.txt
TypeCobol/Compiler/CodeElements/Expressions/StorageArea.cs

WI #1919 Fix CALL profile for special register properties

---

Codegen/src/Generators/DefaultGenerator.cs
TypeCobol.Test/Parser/Scanner/ResultFiles/TCKeywords-AsCobol85.txt
TypeCobol.Test/Parser/Scanner/ResultFiles/TCKeywords-AsTypeCobol.txt
TypeCobol.Test/Parser/Scanner/TestTokenTypes.cs
TypeCobol/Compiler/Scanner/Scanner.cs
TypeCobol/Compiler/Scanner/TokenUtils.cs
TypeCobol/Compiler/Text/CobolTextLine.cs

WI #1964 Exclude TC keywords while parsing in pure Cobol mode

---

TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs

Insta-fix for #1990.
No unit test but checked live in editor.

WI #1990 Fix type comparison in procedure call checker

---

TypeCobol.LanguageServer/Workspace.cs

** What have been done**
It is necessary to clear the COPY cache.

WI #2070 Clear Copy Cache

---

TypeCobol.Analysis/Graph/CfgAbstractInterpretation.Environment.cs

This is complement to #2050 to simplify `Environment` class.
- no need to compute domain before running graph reduction algorithm
- simplify checks keeping only `CanExecute`
- style and readability improvements

WI #2045 Simplify abstract interpretation class

---

TypeCobol.Test/Parser/Programs/Cobol85/AbbrevExprression.rdz.cbl
TypeCobol.Test/Parser/Programs/Cobol85/AbbrevExprression.rdzPGM.txt
TypeCobol/AntlrGrammar/CobolExpressions.g4
TypeCobol/Compiler/Parser/CodeElementBuilder/CobolExpressionsBuilder.cs

**What have been done**
- The ANTLR grammar of abbreviated expression is changed.
- CobolExpressionBuilder is adapted 
- AbbrevExpression test is added.

WI #2083 Allow the syntax of abbreviated expression

---

TypeCobol/TypeCobol.csproj

WI #2101 Use ANTLR C# code generator .NET implementation instead of Java

---

TypeCobol.LanguageServer/JsonRPC/JsonRPCServer.cs
TypeCobol.LanguageServer/TypeCobol.LanguageServer.csproj
TypeCobol.LanguageServer/VsCodeProtocol/Initialize Method/InitializedNotification.cs
TypeCobol.LanguageServer/VsCodeProtocol/Initialize Method/InitializedParams.cs
TypeCobol.LanguageServer/VsCodeProtocol/LanguageServer.cs
TypeCobol/Compiler/CupPreprocessor/CobolCompilerDirectivesParser.cs

Fix #2109 
Contains also missing change from #2074.

2109 minor bugs lsp

---

TypeCobol.Test/Parser/Programs/Cobol85/CommonProgramAttributes.rdz.cbl
TypeCobol.Test/Parser/Programs/Cobol85/CommonProgramAttributes.rdzMix.txt
TypeCobol.Test/Parser/Programs/Cobol85/RecursiveProgramAttributes.rdz.cbl
TypeCobol.Test/Parser/Programs/Cobol85/RecursiveProgramAttributes.rdzMix.txt
TypeCobol/Compiler/Diagnostics/CrossChecker.cs

WI #2044 Check usage of common and recursive attributes

---

TypeCobol.Test/Parser/Preprocessor/DirectiveResultFiles/ExecSqlInclude.txt
TypeCobol.Test/Parser/Programs/Cobol85/ExecSql/ExecSqlWithFromClause.rdz.cbl
TypeCobol.Test/Parser/Programs/Cobol85/ExecSql/ExecSqlWithFromClause.rdzMix.txt
TypeCobol.Test/Parser/Programs/Cobol85/ExecSql/ExecSqlWithSelectDotStar.rdz.cbl
TypeCobol.Test/Parser/Programs/Cobol85/ExecSql/ExecSqlWithSelectStar.rdz.cbl
TypeCobol.Test/Parser/Programs/Cobol85/ExecSql/ExecSqlWithSelectStar.rdzMix.txt
TypeCobol/AntlrGrammar/CobolCodeElements.g4
TypeCobol/Compiler/CodeElements/Expressions/StorageArea.cs
TypeCobol/Compiler/Sql/CodeElements/SqlCodeElementBuilder.cs
TypeCobol/Compiler/Sql/Model/FromClause.cs
TypeCobol/Compiler/Sql/Model/TableReference.cs
TypeCobol/Compiler/Sql/Scanner/SqlScanner.cs
TypeCobol/Compiler/Sql/VisitorPattern.cs

WI #2155 Integrate From Clause

---

TypeCobol/Compiler/Diagnostics/CrossChecker.cs
TypeCobol/Logging/LoggingSystemExtensions.cs

Temporary debug code for #2266.

WI #2266 Add temporary debug code for IF nodes without children

---

TypeCobol.Test/Parser/Preprocessor/DirectiveResultFiles/Copy.txt
TypeCobol.Test/Parser/Preprocessor/DirectiveTestFiles/Copy.cbl
TypeCobol/Compiler/CupPreprocessor/CompilerDirectiveBuilder.cs
TypeCobol/Compiler/Preprocessor/PreprocessorStep.cs

WI #2226 Reset CompilerDirective builder between directives on same line

---

TypeCobol.LanguageServer/WorkspaceProjectStore.cs
TypeCobol/Compiler/CompilationProject.cs

WI #2351 Clear copy cache for default WorkspaceProject when last document is closed

---

TypeCobol.Test/Parser/Programs/Cobol85/InvalidReplace2.rdz.cbl
TypeCobol.Test/Parser/Programs/Cobol85/InvalidReplace2.rdzMix.txt
TypeCobol/Compiler/Scanner/Scanner.cs

WI #2374 Allow comma as separator between REPLACE clauses

---

TypeCobol.Test/Parser/Scanner/ResultFiles/NumericLiterals.txt
TypeCobol.Test/Parser/Scanner/TestTokenTypes.cs
TypeCobol/Compiler/Scanner/AbstractScanner.cs

WI #2387 Fix numeric literal creation when decimal part is missing

---

TypeCobol/Compiler/CompilationDocument.cs
TypeCobol/Compiler/CompilationUnit.cs
TypeCobol/Compiler/Parser/CodeElementsParserStep.cs
TypeCobol/Compiler/Parser/ProgramClassParserStep.cs
TypeCobol/Compiler/Preprocessor/PreprocessorStep.cs

WI #2372 Improve accuracy of performance counters

---

TypeCobol.Test/Utils/Comparator.cs
TypeCobol/Compiler/IncrementalChangesHistory.cs

This is to compare with PR #2395.

WI #2391 Introduce incremental changes history

---

TypeCobol.Test/Parser/Programs/Cobol85/SearchAllWhenDuplicateKey.rdz.cbl
TypeCobol.Test/Parser/Programs/Cobol85/SearchAllWhenDuplicateKey.rdzPGM.txt
TypeCobol/Compiler/Diagnostics/CodeElementCheckers.cs
TypeCobol/Compiler/Parser/CodeElementBuilder/CobolCodeElementBuilder.cs

WI #2393 Check for duplicate sorting keys in OCCURS clause

---

TypeCobol/Compiler/CompilationUnit.cs
TypeCobol/Compiler/CupParser/NodeBuilder/ProgramClassBuilder.cs
TypeCobol/Compiler/Parser/ProgramClassParserStep.cs

Replaces #2425, now targeting master.

WI #2185 #2319 Add last 5 incremental changes into debug trace

---

TypeCobol/Compiler/CupParser/NodeBuilder/ProgramClassBuilder.cs

Could be vastly optimized as we iterate twice over the lines to create the multiple logs...

WI #2185 #2319 Split file structure and source code into multiple traces

---

TypeCobol/Compiler/CompilationDocument.cs
TypeCobol/Compiler/CompilationUnit.cs
TypeCobol/Compiler/Parser/CodeElementsLine.cs
TypeCobol/Compiler/Preprocessor/ProcessedTokensLine.cs
TypeCobol/Compiler/Scanner/ITokensLine.cs
TypeCobol/Compiler/Scanner/TokensLine.cs

WI #2440 Optimize diagnostics collection

---

TypeCobol/Compiler/Preprocessor/PreprocessorStep.cs

Fixes #2442.
Work item reference in commit message is wrong but this will be ok in resulting squash.

WI #2442 Optimize line iteration in PreprocessorStep

---

TypeCobol.Test/Parser/Incremental/TestIncrementalPipeline.cs
TypeCobol.Test/Utils/AutomaticIncrementalChangesStrategies.cs

7 excluded tests :
- 5 already described in #2467 
- 2 new introduced with #2474

WI #2467 Add change generator for document rewriting in reverse order

---

TypeCobol/Compiler/CompilationDocumentCache.cs

WI #2546 Fix bug in copy eviction process after receiving DidChangedW…atchedFiles

---

TypeCobol.LanguageServer.Test/LSRTest.cs
TypeCobol.LanguageServer.Test/LSRTests/EI_ExtractRemarksData_DebugLines/input/CpyCopies.lst
TypeCobol.LanguageServer.Test/LSRTests/EI_ExtractRemarksData_DebugLines/input/EI_ExtractRemarksData_DebugLines.tlsp
TypeCobol.LanguageServer.Test/LSRTests/EI_ExtractRemarksData_DebugLines/output_expected/EI_ExtractRemarksData_DebugLines.rlsp
TypeCobol.LanguageServer/Workspace.cs

Code report for #2556 passed as hotfix.

Code report

---

TypeCobol.Test/Parser/Scanner/ScannerUtils.cs
TypeCobol/Compiler/CodeModel/SymbolTable.cs
TypeCobol/Compiler/CompilationDocument.cs
TypeCobol/Compiler/CompilationUnit.cs
TypeCobol/Compiler/Concurrency/ImmutableList.cs
TypeCobol/Compiler/Parser/CodeElementsParserStep.cs
TypeCobol/Compiler/Parser/ICodeElementsLine.cs
TypeCobol/Compiler/Preprocessor/PreprocessorStep.cs
TypeCobol/Compiler/Scanner/ScannerStep.cs

Prapratory work for #2236.
Replaces #2371.

WI #2236 Limit uses of ImmutableList<T>

---

TypeCobol.Test/Parser/Programs/Cobol85/SortStatement.Mix.txt
TypeCobol/Compiler/Diagnostics/CrossChecker.cs
TypeCobol/Compiler/Parser/CodeElementBuilder/CobolExpressionsBuilder.cs

This is not complete as we still need to check subscripts manually for SORT statement.
This wasn't done before so I propose to merge only that for now while keeping #2591 open.

WI #2591 Capture storage area for SORT statement

---

TypeCobol.Test/Parser/Programs/Cobol85/RedefinesWithTransitivity.MEM.txt
TypeCobol.Test/Parser/Programs/Cobol85/RedefinesWithTransitivity.rdz.cbl
TypeCobol/Compiler/CodeModel/SymbolTable.cs
TypeCobol/Compiler/Diagnostics/Cobol2002Checker.cs
TypeCobol/Compiler/Nodes/Data.cs

Fix #2594 transitive REDEFINES problem (wrong physical length)

---

TypeCobol/Compiler/Nodes/Data.cs

WI #2602 Fix NullRefException in DataDefinition.StartPosition property

---

TypeCobol/Compiler/Nodes/Data.cs

WI #2619 Optimize the StartPosition property

---

TypeCobol.LanguageServer.Test/LSRTest.cs
TypeCobol.LanguageServer.Test/LSRTests/ExecuteCommandRefactorAdjustFillers_WithCopy/input/CopyFolder/YMYCOPY.cpy
TypeCobol.LanguageServer.Test/LSRTests/ExecuteCommandRefactorAdjustFillers_WithCopy/input/ExecuteCommandRefactorAdjustFillers_WithCopy.tlsp
TypeCobol.LanguageServer.Test/LSRTests/ExecuteCommandRefactorAdjustFillers_WithCopy/output_expected/ExecuteCommandRefactorAdjustFillers_WithCopy.rlsp
TypeCobol.LanguageServer/Commands/AdjustFillers.cs

WI #2642 Ignore REDEFINES coming from included copy(s) when adjusting FILLERs

---

TypeCobol/Logging/LoggingSystem.cs

WI #2656 Use ConsoleLogger as last resort for pending logs on exit

---

TypeCobol.LanguageServer/TypeCobolServer.cs
TypeCobol.LanguageServer/VsCodeProtocol/Text Document Notifications/DidChangeTextDocumentParams.cs
TypeCobol.LanguageServer/VsCodeProtocol/Text Document/VersionedTextDocumentIdentifier.cs

Some LSP classes are not compatible with the specifications of LSP 3.17

WI #2659 Fix LSP incompatibilities

---

TypeCobol.Analysis.Test/Violation/TestCreation-expected.txt
TypeCobol.Analysis.Test/Violation/TestCreation-input.txt
TypeCobol.Analysis.Test/ViolationTest.cs
TypeCobol/Analysis/Violation.cs
TypeCobol/Tools/Strings.cs

WI #2666 Fix FormatException when creating violation from analyzer

---

TypeCobol/Logging/LoggingSystem.cs

Part of #2668.
Simplify logging system by replacing the polling mechanism with a signal.

WI #2668 Improve asynchronous logging by using AutoResetEvent

---

CLI/test/ressources/arguments_errors_1/ExpectedConsole.txt
CLI/test/ressources/arguments_errors_2/ExpectedConsole.txt
CLI/test/ressources/arguments_errors_3/ExpectedConsole.txt
CLI/test/ressources/dependencies_4/ExpectedConsole.txt
TypeCobol.LanguageServer/TypeCobolServerHost.cs
TypeCobol.Transform/Decoder.cs
TypeCobol.Transform/Transform.cs
TypeCobol/Tools/Options-Config/TypeCobolConfiguration.cs

Note that this PR contains breaking changes !
Clients testing return codes further than a comparison to 0 must be adapted.

WI #2681 Change return codes for CLI / LanguageServer / Transform

---

TypeCobol.LanguageServer.Test/ProcessorTests/DataLayout/CSV-simple.txt
TypeCobol.LanguageServer.Test/ProcessorTests/DataLayout/CSV-stackedAndNested.txt
TypeCobol.LanguageServer.Test/ProcessorTests/DataLayout/simple.cbl
TypeCobol.LanguageServer.Test/ProcessorTests/DataLayout/stackedAndNested.cbl
TypeCobol.LanguageServer.Test/ProcessorTests/DataLayoutProcessorCSVTest.cs
TypeCobol.LanguageServer.Test/TypeCobol.LanguageServer.Test.csproj
TypeCobol.LanguageServer/Processor/DataLayoutProcessor.cs
TypeCobol.LanguageServer/Workspace.cs

WI #2686 Implement tests outside LSP for GetDataLayout

---

Codegen/src/Actions/Qualifier.cs
Codegen/src/Generator.cs
Codegen/src/Generators/DefaultGenerator.cs
Codegen/src/Generators/ExpandingCopyGenerator.cs
Codegen/src/Generators/LinearNodeSourceCodeMapper.cs

This is a supplementary PR over #2690 containing the refactoring of node positions in Codegen.

WI #2674 Introduce NodePositions record class to improve readability

---

TypeCobol.LanguageServer.Test/ProcessorTests/DataLayout/CSV-CopyWithout01.txt
TypeCobol.LanguageServer.Test/ProcessorTests/DataLayout/Tree-CopyWithout01.txt
TypeCobol.LanguageServer.Test/ProcessorTests/DataLayout/copyWithout01.cpy
TypeCobol.LanguageServer.Test/ProcessorTests/DataLayoutProcessorCSVTest.cs
TypeCobol.LanguageServer.Test/ProcessorTests/DataLayoutProcessorTreeTest.cs
TypeCobol.LanguageServer/Processor/DataLayoutProcessor.cs
TypeCobol.LanguageServer/TypeCobolCustomLanguageServer/Get Data Layout Request/DataLayoutNode.cs

WI #2711 Fix CSV data layout for COPYs not having their own 01

---

TypeCobol.Test/Parser/Programs/TypeCobol/TypedefNames.Mix.rdz.tcbl
TypeCobol.Test/Parser/Programs/TypeCobol/TypedefNames.PGM.txt
TypeCobol/Compiler/Diagnostics/CodeElementCheckers.cs

WI #2714 Do not check TYPEDEFs name lengths

---

TypeCobol.Test/Parser/Programs/TypeCobol/TypedefNames.Mix.rdz.tcbl
TypeCobol.Test/Parser/Programs/TypeCobol/TypedefNames.PGM.txt
TypeCobol/Compiler/Diagnostics/CodeElementCheckers.cs

Same as #2715 but with improved syntax coming from C# 9

WI #2714 Report hotfix

---

TypeCobol.LanguageServer.Test/RefactoringTests/InsertVariableDisplay/TextBeyondInsertionPoint/DotAfterStatement.cbl
TypeCobol.LanguageServer.Test/RefactoringTests/InsertVariableDisplay/TextBeyondInsertionPoint/TwoStatementsOnSameLineInsertAfterFirst.cbl
TypeCobol.LanguageServer.Test/RefactoringTests/InsertVariableDisplay/TextBeyondInsertionPoint/TwoStatementsOnSameLineInsertAfterSecond.cbl
TypeCobol.LanguageServer.Test/RefactoringTests/InsertVariableDisplay/TextBeyondInsertionPoint/TwoStatementsOnSameLineInsertBeforeFirst.cbl
TypeCobol.LanguageServer.Test/RefactoringTests/InsertVariableDisplay/TextBeyondInsertionPoint/TwoStatementsOnSameLineInsertBeforeSecond.cbl
TypeCobol.LanguageServer/Commands/InsertVariableDisplay/CobolStringBuilder.cs
TypeCobol.LanguageServer/Commands/InsertVariableDisplay/InsertVariableDisplayRefactoringProcessor.cs

WI #2733 Fix InsertVariableDisplay mechanism to correctly align text following insertion point

---

TypeCobol.LanguageServer.Test/RefactoringTests/InsertVariableDisplay/NotDisplayable/DoNotSelectNonDisplayables.cbl
TypeCobol.LanguageServer/Commands/InsertVariableDisplay/DataDefinitionToDisplayVisitor.cs
TypeCobol.LanguageServer/Commands/InsertVariableDisplay/IndexGenerator.cs
TypeCobol.LanguageServer/Processor/DataLayoutProcessor.cs
TypeCobol.LanguageServer/TypeCobolCustomLanguageServer/Get Data Layout Request/DataLayoutNode.cs
TypeCobol/Compiler/CupParser/NodeBuilder/ProgramClassBuilder.cs
TypeCobol/Compiler/Nodes/Node.cs

WI #2736 Compute useful flags for InsertVariableDisplay while building Nodes

---

TypeCobol.LanguageServer/Context/UnknownDocumentException.cs
TypeCobol.LanguageServer/TypeCobolCustomLanguageServer/TypeCobolCustomLanguageServer.cs
TypeCobol/Compiler/FileCompiler.cs
TypeCobol/Compiler/Nodes/Attributes.cs
TypeCobol/Compiler/Nodes/Documentation.cs

WI #2721 Avoid using untyped exceptions

---

TypeCobol.LanguageServer.Test/ProcessorTests/DataLayout/CSV-CopyAtBeginning.txt
TypeCobol.LanguageServer.Test/ProcessorTests/DataLayout/CSV-CopyWithout01AtBeginning.txt
TypeCobol.LanguageServer.Test/ProcessorTests/DataLayout/CSV-SimplePgmAtBeginning.txt
TypeCobol.LanguageServer.Test/ProcessorTests/DataLayout/Tree-CopyAtBeginning.txt
TypeCobol.LanguageServer.Test/ProcessorTests/DataLayout/Tree-CopyWithout01AtBeginning.txt
TypeCobol.LanguageServer.Test/ProcessorTests/DataLayout/Tree-SimplePgmAtBeginning.txt
TypeCobol.LanguageServer.Test/ProcessorTests/DataLayoutProcessorCSVTest.cs
TypeCobol.LanguageServer.Test/ProcessorTests/DataLayoutProcessorTreeTest.cs
TypeCobol.LanguageServer/Processor/DataLayoutProcessor.cs
TypeCobol.LanguageServer/Utilities/CodeElementLocator.cs

WI #2768 Handle cursor positioned before main program or at beginning of copy in DataLayout

---

TypeCobol.LanguageServer.Test/ProcessorTests/Completion/AfterIn/Chain1.txt
TypeCobol.LanguageServer.Test/ProcessorTests/Completion/AfterIn/Chain2.txt
TypeCobol.LanguageServer.Test/ProcessorTests/Completion/AfterIn/Filler.txt
TypeCobol.LanguageServer.Test/ProcessorTests/Completion/AfterIn/NotImplemented.txt
TypeCobol.LanguageServer.Test/ProcessorTests/Completion/AfterIn/SeveralParents.txt
TypeCobol.LanguageServer.Test/ProcessorTests/Completion/AfterIn/Variable.txt
TypeCobol.LanguageServer.Test/ProcessorTests/Completion/AfterMove/NamesUsingHyphens.txt
TypeCobol.LanguageServer.Test/ProcessorTests/Completion/AfterOf/NotImplemented.txt
TypeCobol.LanguageServer.Test/ProcessorTests/CompletionProcessorTest.cs
TypeCobol.LanguageServer/Completion Factory/CodeElementMatcher.cs
TypeCobol.LanguageServer/Completion Factory/CompletionFactoryHelpers.cs
TypeCobol.LanguageServer/Completion Factory/CompletionForInOrOf.cs
TypeCobol.LanguageServer/Processor/CompletionProcessor.cs

WI #2717 Implement completion after IN

---

TypeCobol.LanguageServer.Test/ProcessorTests/Completion/AfterUnsupportedKeyword/InsideKeyword.txt
TypeCobol.LanguageServer.Test/ProcessorTests/Completion/AfterUnsupportedKeyword/RightAfterKeyword.txt
TypeCobol.LanguageServer.Test/ProcessorTests/Completion/AtBeginningOfLine/KeywordNoUserFilter.txt
TypeCobol.LanguageServer.Test/ProcessorTests/Completion/AtBeginningOfLine/KeywordNoUserFilterEI.txt
TypeCobol.LanguageServer.Test/ProcessorTests/Completion/AtBeginningOfLine/KeywordUserFilter1.txt
TypeCobol.LanguageServer.Test/ProcessorTests/Completion/AtBeginningOfLine/KeywordUserFilter1EI.txt
TypeCobol.LanguageServer.Test/ProcessorTests/Completion/AtBeginningOfLine/KeywordUserFilter2.txt
TypeCobol.LanguageServer.Test/ProcessorTests/Completion/AtBeginningOfLine/KeywordUserFilter2EI.txt
TypeCobol.LanguageServer.Test/ProcessorTests/Completion/AtBeginningOfLine/KeywordUserFilter3.txt
TypeCobol.LanguageServer/Completion Factory/CompletionForKeywords.cs

WI #2789 Suggest END-xxx keyword according to user filter text
