- TypeCobol.Test/Compiler/CodeElements/ArithmeticStatementTester.cs
- TypeCobol/Compiler/CodeElements/Statement/AddStatement.cs
- TypeCobol/Compiler/CodeElements/Symbols/DataName.cs
- TypeCobol/Compiler/Parser/CodeElementBuilder.cs
Seen in https://github.com/wiztigers/TypeCobol/commit/c79e1fc97997523c03b30b316647332e95f5d759 and https://github.com/wiztigers/TypeCobol/commit/4a563167a9dbdb8e35f72a6ff0fa3c8f4e84be69
Traced in [issue 3] (https://github.com/wiztigers/TypeCobol/issues/3)
Dictionnary AddStatement.affectations now use proper SymbolReferences instead of Tokens.
> Use SymbolReferences

- TypeCobol.Grammar/Grammars/Cobol/CobolCodeElements.g4
- TypeCobol/Compiler/Parser/CodeElementBuilder.cs
Seen in [ef784cb] (https://github.com/wiztigers/TypeCobol/commit/ef784cbb11d0026bb5a091df689aa78bd00181b0)
Traced in https://github.com/wiztigers/TypeCobol/issues/6
Grammar now says explicitely that only 'numeric' literals can be in ADD statement.
> Numeric Literals only in the grammar's ADD rule

- TypeCobol.Test/Compiler/Parser/ResultFiles/Statements/MOVE.txt
- TypeCobol.Test/Compiler/Parser/Samples/Statements/MOVE.cbl
- TypeCobol.Test/Compiler/Scanner/ResultFiles/AlphanumericLiterals-continuations.txt
- TypeCobol.Test/Compiler/Scanner/TestContinuations.cs
- TypeCobol/Compiler/Scanner/Token.cs
in Token class, a ContinuationToken should always keep a channel value of CHANNEL_ContinuationTokens (to be filtered before the parsing stage), even if it is itself continued (because it is in the middle of a list of continuation lines).
The Scanner and Parser tests suites have been augmented with the tests case given in the issue #60.
> Fixed issue #60

- TypeCobol.Grammar/Grammars/Cobol/CobolCodeElements.g4
- TypeCobol.Grammar/TypeCobol.Grammar.csproj
- TypeCobol.Grammar/packages.config
- TypeCobol.Test/Compiler/Preprocessor/DirectiveResultFiles/Copy.txt
- TypeCobol.Test/TypeCobol.Test.csproj
- TypeCobol.Test/packages.config
- TypeCobol/Compiler/Parser/CodeElementBuilder.cs
- TypeCobol/Compiler/Parser/LogicalExpressionBuilder.cs
- TypeCobol/Compiler/Parser/StatementsBuilder.cs
- TypeCobol/TypeCobol.csproj
- TypeCobol/packages.config
- TypeCobolStudio/TypeCobolStudio.csproj
- TypeCobolStudio/packages.config
Fixed CodeElementBuilders source code to handle the following breaking change in Antlr v4.5 : "ParserRuleContext.GetTokens  now returns  ITerminalNode[]  in all runtimes (previously .NET 4.5+ did not)" => replaced IList.Count by Array.Length everywhere.
Spotted a typo in the grammar : "LINEAGE" instead of "LINAGE" => also fixed this error on the fly.
> Upgraded references to Antlr Nuget packages : version 4.4 => 4.5.

- TypeCobol.Test/TestCollection.cs
- TypeCobol/Compiler/AntlrUtils/DiagnosticSyntaxErrorListener.cs
- TypeCobol/Compiler/CodeElements/CodeElement.cs
- TypeCobol/Compiler/CodeElements/CodeElementType.cs
- TypeCobol/Compiler/CompilationDocument.cs
- TypeCobol/Compiler/CompilationUnit.cs
- TypeCobol/Compiler/Parser/CodeElementsParserStep.cs
- TypeCobol/Compiler/Parser/ProgramClassBuilder.cs
- TypeCobol/Compiler/Parser/ProgramClassParserStep.cs
- TypeCobol/Compiler/Preprocessor/PreprocessorStep.cs
The test TestPaser.Check_BeforeAfterInsertion() now runs correctly.
Main fixes for issue 124 :
- copy/paste error : choosed the wrong list of lines as a starting point when initializing the CodeElements parsing step
- the incremental parsing of CodeElements is not implement yet, so we must reset all CodeElements each time before starting to parse again
Main fixes for issue 125 : 
- bad channel number returned by CodeElement when used as IToken
- CodeElementType values were starting at 0 while the enumeration of tokens in an Antlr grammar is always transformed in a list of values starting at 1
> Fixes issues #124 and #125 for incremental parsing

- TypeCobol/Compiler/Concurrency/DocumentVersion.cs
- TypeCobol/Compiler/Preprocessor/PreprocessorStep.cs
- TypeCobol/Compiler/Scanner/ScannerStep.cs
Small changes in DocumentVersion.GetReduceddAndOrderedChangesInNewerVersion, ScannerStep.ScanTokensLineWithMultilineScanState, PreprocessorStep.CheckIfAdjacentLinesNeedRefresh
> Fix for issue #141 : correct small typos for test Check_BeforeAfterInsertionBatched

- TypeCobol.Test/Compiler/Parser/Comparator.cs
FolderTester now counts the number of Compartor run instead of the number of input files to test
> FolderTester now counts the number of Compartor run 

- Codegen/src/Actions/Qualifier.cs
- Codegen/src/Generators/SignaturesGenerator.cs
- TypeCobol/Compiler/CodeElements/CobolLanguageLevelVisitor.cs
- TypeCobol/Compiler/Nodes/Node.cs
- only CodeGen visitor will make a copy of Node's children before visit, as it can modify them
> WI #1051 Optimize visitor on children nodes

- .gitignore
- CSCup/CSCup.csproj
- CSCup/emit.cs
- CSCup/parser.cs
- CSCup/production.cs
- CSCupRuntime/CSCupRuntime.csproj
- CSCupRuntime/StackList.cs
- CSCupRuntime/lr_parser.cs
- CSCupRuntime/virtual_parse_stack.cs
- TypeCobol.Test/Parser/Performance/Performance.cs
- TypeCobol.Test/TestUtils.cs
- TypeCobol/Compiler/CupCommon/CupCobolErrorStrategy.cs
- TypeCobol/Compiler/CupCommon/ICupParserErrorReporter.cs
- TypeCobol/Compiler/CupParser/NodeBuilder/CupParserTypeCobolProgramDiagnosticErrorReporter.cs
- TypeCobol/Compiler/CupParser/TypeCobolProgram.cup
- TypeCobol/Compiler/CupParser/TypeCobolProgramParser.cs
- TypeCobol/Compiler/CupPreprocessor/CobolCompilerDirectives.cup
- TypeCobol/Compiler/CupPreprocessor/CobolCompilerDirectivesParser.cs
- TypeCobol/Compiler/CupPreprocessor/CompilerDirectiveErrorStrategy.cs
Make CUP runtime 25% faster by using :
- Generics in the internal stack of the runtime
- Implemented method to access an element in the middle of the stack. This avoid to copy the stack to an array.
- The Stack has been duplicated from source code of .Net framework
As node phase (which use CUP runtime) is already fast, the global gain is only 3% for full parsing and 7% for incremental parsing.
> Make CUP runtime 25% faster

- TypeCobol/Compiler/CupParser/NodeBuilder/ProgramClassBuilder.cs
- TypeCobol/Compiler/Diagnostics/Cobol2002Checker.cs
- TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs
On a source that used to take 30 seconds to generate, we win 5 to 8 seconds
> WI #1247 Remove useless track of events

- TypeCobol.Test/Parser/Programs/TypeCobol/CircularReferenceType.rdzMix.txt
- TypeCobol.Test/Parser/Programs/TypeCobol/CircularReferenceType.rdzPGM.txt
- TypeCobol/Compiler/CodeModel/SymbolTable.cs
- TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs
- TypeCobol/Compiler/Diagnostics/TypeCobolLinker.cs
Issues : #1294 #1301 #1302 #1114 
Here's a first set of optimization mainly focused on SymbolTable and one commit about TypeCobolLinker.
You can look at each commit separatly to understand the optimization done.
Gain obtained on each performance test:
_Note : One of the major optimization is only valid for unused variables.
So depending on the source file, you won't get the same result._
|                                                       |      | 
|-------------------------------------------------------|------| 
| Test                                                  | Gain | 
| Part1_FullParsing_Cobol85_NoRedefines                 | 6%   | 
| Part1_FullParsing_TC_BigTypesNoProcedure              | 34%  | 
| Part1_FullParsing_TC_BigTypesWithProcedure            | 18%  | 
| …
> WI #1301 Optimize symbol table

- TypeCobol.Test/Parser/Programs/TypeCobol/FunctionsDeclaration.rdzPGM.txt
- TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureCall.rdzPGM.txt
- TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs
- TypeCobol/Compiler/Nodes/Procedure.cs
Checkers don't need to be called for each ParameterDescription.
> Fix #1292 ASTVisitor now visit parameters of FunctionDeclaration

- TypeCobol/Compiler/CodeElements/Entry/DataType.cs
- TypeCobol/Compiler/Diagnostics/Cobol2002Checker.cs
- TypeCobol/Compiler/Diagnostics/CrossChecker.cs
- TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs
#1303
- Checker Visitor now use the most derivated method.
- Instead of calling some checkers on "BeginNode" method, call them with the most derivated method.
- DataDefinition : Only use last child to detect children that declare data
WI #1294 Misc optimization for DataType.Equals
Use StringComparison.OrdinalIgnoreCase instead to convert the string to uppercase.
Performance gain:
|                                                       |      | 
|-------------------------------------------------------|------| 
| Test                                                  | Gain | 
| Part1_FullParsing_Cobol85_NoRedefines                 | 2%   | 
| Part1_FullParsing_TC_BigTypesNoProcedure              | 2%   | 
| Part1_FullParsing_TC_BigTypesWithProcedure            | 5%   | 
| …
> WI #1303 #1294 Checker and DataType.Equals optimizations

- Codegen/test/TestTypeCobolCodegen.cs
- Codegen/test/resources/input/TypeCobol/PreserveLineBreaksAndIndents.rdz.tcbl
- Codegen/test/resources/output/TypeCobol/PreserveLineBreaksAndIndents.rdz.tcbl
- TypeCobol/Compiler/Text/CobolTextLine.cs
Fix for issue #1552.
The idea behind this fix is that the line breaks added by `TypedDataNode.FlushConsumedTokens` were not considered as line breaks but as standard characters. This would lead to errors when splitting based on length. Now the splitting process starts by splitting over line breaks and then apply length restrictions.
> 1552 unwanted line breaks

- CLI/test/CLITest.cs
- CLI/test/ressources/outputSignature_1/output_expected/ProcedureCall-Public-Signatures.rdz.tcbl
- CLI/test/ressources/outputSignature_3/CLIArguments.txt
- CLI/test/ressources/outputSignature_3/input/Library.rdz.tcbl
- CLI/test/ressources/outputSignature_3/output_expected/Client.rdz.tcbl
- CLI/test/ressources/outputSignature_3/output_expected/error.txt
- Codegen/src/Generators/SignaturesGenerator.cs
- TypeCobol.Test/Parser/Programs/TypeCobol/GlobalStorageSection.rdz.tcbl
- TypeCobol.Test/Parser/Programs/TypeCobol/GlobalStorageSection.rdzMix.txt
- TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs
* WI #1629 Check that GlobalStorage is not declared inside procedures
* WI #1624 #1636 Keep formalized comments while exporting public signatures
> Update v1.4.1 with missing commits from v1.4

- Codegen/src/Actions/Qualifier.cs
- Codegen/src/Actions/Replace.cs
- Codegen/src/Actions/ReplaceCode.cs
- Codegen/test/resources/input/TypeCobol/Global_Storage/GlobalStorageWithTypedefAndIndex.rdz.tcbl
- Codegen/test/resources/output/TypeCobol/Global_Storage/GlobalStorageWithTypedefAndIndex.rdz.tcbl
Partial fix for #1718.
This PR tackles the wrong index names in SET statements only.
See [1718_WrongIndexNames_FixIdeaForCALLs](https://github.com/TypeCobolTeam/TypeCobol/tree/1718_WrongIndexNames_FixIdeaForCALLs) branch for a possible fix for CALLs.
> WI #1718 Fix wrong generated index names in SET statements

- CLI/test/CLITest.cs
- CLI/test/ressources/dependenciesSignatureOverload/CLIArguments.txt
- CLI/test/ressources/dependenciesSignatureOverload/input/Dependency.tcbl
- CLI/test/ressources/dependenciesSignatureOverload/input/Main.tcbl
- CLI/test/ressources/dependenciesSignatureOverload/output_expected/Main.cbl
- CLI/test/ressources/dependenciesSignatureOverload/output_expected/errors.txt
- TypeCobol.Test/Parser/Programs/TypeCobol/FunctionsDeclaration.rdzPGM.txt
- TypeCobol/Compiler/CodeElements/Expressions/StorageArea.cs
- TypeCobol/Compiler/CodeElements/Header/FunctionDeclarationHeader.cs
- TypeCobol/Compiler/CodeModel/SymbolTable.cs
- TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs
- TypeCobol/Compiler/Nodes/ParametersProfileNode.cs
Fixes #1747.
The fix uses the TypeDefinition and DataType (instead of DataType only) to improve overload resolution.
Also include some renaming.
> WI #1747 Use TypeDefinition to improve overload resolution

- TypeCobol.Analysis.Test/BasicCfgPrograms/HanoiPrg.dot
- TypeCobol.Analysis.Test/DfaBuildUseAndDefListTest.cs
- TypeCobol.Analysis.Test/DfaCallPgmReport.cs
- TypeCobol.Analysis.Test/Report/ProcCallPgm.cbl
- TypeCobol.Analysis.Test/Report/ProcCallPgm.csv
- TypeCobol.Analysis/Dfa/DataFlowGraphBuilder.cs
- TypeCobol.Analysis/Dfa/DefaultDataFlowGraphBuilder.cs
- TypeCobol.Analysis/Dfa/ValueOrigin.cs
**Purpose**
This Pull request is based on branch 
https://github.com/TypeCobolTeam/TypeCobol/compare/1260_CFG_DFA_SemanticDomainLite_IntegrateAsAnalyzer
To allow Data Definition having values and declared in the DataDivision of a Program to be put as instruction nodes in the START block of the corresponding PROCEDURE DIVISION.
So that their intial values are correctly propagated by DFA algorithms from the START block.
> WI #1750 Add DataDefinition nodes having initial value to START Block.

- TypeCobol/Analysis/Violation.cs
- TypeCobol/Compiler/CodeElements/ASTAnalyzerBase.cs
- TypeCobol/Compiler/CupParser/NodeBuilder/SyntaxDrivenAnalyzerBase.cs
- TypeCobol/Compiler/Diagnostics/Diagnostic.cs
- TypeCobol/Compiler/Diagnostics/DiagnosticMessage.cs
- TypeCobol/Compiler/Diagnostics/MessageCode.cs
- TypeCobol/Compiler/Diagnostics/Resources/DiagnosticMessages.csv
Minimal implementation of `Violation` concept :
- no change in API, violations are still handled as regular diagnostics through the whole process
- the new `Violation` class can be used by analyzer implementers to represent a quality rule violation
- `RuleId` is transported as 'source' in LSP diagnostic object
- all rule violations are identified by the same reserved 'code' (47)
> WI #1837 Add Violation class

- TypeCobol.Test/Parser/Programs/Cobol85/ReplaceTokenInsideDataDiv2.rdz.cbl
- TypeCobol.Test/Parser/Programs/Cobol85/ReplaceTokenInsideDataDiv2.rdzSYM.txt
- TypeCobol/Compiler/Preprocessor/ReplaceTokensLinesIterator.cs
- TypeCobol/Compiler/Scanner/ITokensLine.cs
- TypeCobol/Compiler/Scanner/Scanner.cs
- TypeCobol/Compiler/Scanner/Token.cs
This fix handle the case when a replace occurs inside a DataDivision and the replaced token is scan state dependent:
```cobol
IDENTIFICATION DIVISION.
PROGRAM-ID. TCOZCHKP.
data division.
working-storage section.
REPLACE
==C-NBRPCB==      BY ==6==.  
01  W-IDTPCB OCCURS C-NBRPCB    PIC X(8).      
END PROGRAM TCOZCHKP.
```
> WI #428 Handle token scan state dependent in DataDivision.

- TypeCobol.Test/Parser/Programs/Cobol85/SelectFile.cbl
- TypeCobol.Test/Parser/Programs/Cobol85/SelectFilePGM.txt
- TypeCobol/Compiler/CodeElements/Entry/FileControlEntry.cs
- TypeCobol/Compiler/CupParser/NodeBuilder/ProgramClassBuilder.cs
- TypeCobol/Compiler/Parser/CodeElementBuilder/CobolCodeElementBuilder.cs
- TypeCobol/Compiler/Parser/CodeElementBuilder/CobolWordsBuilder.cs
Fix #1909.
Also corrects same kind of problem with incomplete `ASSIGN` clause.
> WI #1909 Avoid exception on incomplete SELECT statements

- TypeCobol.LanguageServer.Test/LSRTest.cs
- TypeCobol.LanguageServer.Test/LSRTestHelper.cs
- TypeCobol.LanguageServer.Test/LSRTests/DisplayCompletionNoTC/input/DisplayCompletionNoTC.tlsp
- TypeCobol.LanguageServer.Test/LSRTests/DisplayCompletionNoTC/output_expected/DisplayCompletionNoTC.rlsp
- TypeCobol.LanguageServer.Test/LSRTests/SimpleMoveToCompletionNoTC/input/SimpleMoveToCompletionNoTC.tlsp
- TypeCobol.LanguageServer.Test/LSRTests/SimpleMoveToCompletionNoTC/output_expected/SimpleMoveToCompletionNoTC.rlsp
- TypeCobol.LanguageServer/Completion Factory/CompletionFactory.cs
- TypeCobol.LanguageServer/Completion Factory/CompletionFactoryHelpers.cs
- TypeCobol.LanguageServer/TypeCobolServer.cs
Fixes #1941 
Minimal modification to the completion code to avoid `::` qualifier in variable completion suggestions. Does not affect procedures or variables from types that are always considered in a TypeCobol context.
> 1941 do not use tc qualifier for pure cobol completion

- CLI/src/CLI.cs
- TypeCobol.Analysis.Test/BasicCfgInstrs/PerformIdentity.diag
- TypeCobol.Analysis.Test/BasicCfgInstrs/PerformProc1Recursive0.diag
- TypeCobol.Analysis.Test/BasicCfgInstrs/PerformProc2Recursive0.diag
- TypeCobol.Analysis.Test/BasicCfgInstrs/PerformProc3Recursive0.diag
- TypeCobol.Analysis.Test/BasicCfgInstrs/PerformProc4Recursive0.diag
- TypeCobol.Analysis.Test/BasicCfgInstrs/PerformProcIterativeAfterRecursive0.diag
- TypeCobol.Analysis.Test/BasicCfgInstrs/PerformProcIterativeAfterRecursive1.diag
- TypeCobol.Analysis.Test/BasicCfgInstrs/PerformProcIterativeAfterRecursive2.diag
- TypeCobol.Analysis.Test/BasicCfgInstrs/PerformProcIterativeRecursive0.diag
- TypeCobol.Analysis.Test/BasicCfgInstrs/PerformThru2.diag
- TypeCobol.Analysis.Test/BasicCfgInstrs/SG102A.diag
- TypeCobol.Analysis.Test/CfgTestUtils.cs
- TypeCobol.Analysis.Test/PerformanceWithCfg.cs
- TypeCobol.Analysis.Test/PerformanceWithCfgDfa.cs
- TypeCobol.Analysis/Cfg/ControlFlowGraphBuilder.cs
- TypeCobol.Analysis/Cfg/DefaultControlFlowGraphBuilder.cs
- TypeCobol.Analysis/CfgDfaAnalyzerFactory.cs
- TypeCobol.Analysis/Graph/ControlFlowGraph.cs
- TypeCobol.LanguageServer/Workspace.cs
- TypeCobol/Compiler/Directives/TypeCobolOptions.cs
- TypeCobol/Tools/Options-Config/TypeCobolConfiguration.cs
> 2007 optional diag cfg

- TypeCobol.Test/Parser/Preprocessor/PreprocessorUtils.cs
- TypeCobol/Compiler/AntlrUtils/AntlrPerformanceProfiler.cs
- TypeCobol/Compiler/AntlrUtils/TokensLinesTokenStream.cs
- TypeCobol/Compiler/CupCommon/CobolWordsTokenizer.cs
- TypeCobol/Compiler/Parser/CodeElementsLinesTokenSource.cs
- TypeCobol/Compiler/Preprocessor/CopyTokensLinesIterator.cs
- TypeCobol/Compiler/Scanner/ITokensLinesIterator.cs
- TypeCobol/Compiler/Scanner/Token.cs
- TypeCobol/Compiler/Scanner/TokensLinesIterator.cs
- TypeCobol/LanguageServices/CodeAnalysis/Statistics/StatsGenerator.cs
Fix #2026.
Following #2030, this PR removes the data retention caused by static `Token` instance 'END_OF_FILE'.
> WI #2026 Remove static END_OF_FILE token

- TypeCobol.Test/Parser/CodeElements/SEARCH.cbl
- TypeCobol.Test/Parser/Programs/Cobol85/ReferenceModifiers.rdz.cbl
- TypeCobol.Test/Parser/Programs/Cobol85/ReferenceModifiers.rdzMix.txt
- TypeCobol/Compiler/Diagnostics/CodeElementCheckers.cs
- TypeCobol/Compiler/Parser/CodeElementBuilder/CobolExpressionsBuilder.cs
> WI #1991 Check reference modifiers

- TypeCobol.Analysis.Test/BasicCfgInstrs/ExtendedPerformProc3Recursive0.diag
- TypeCobol.Analysis.Test/BasicCfgInstrs/ExtendedPerformProc4Recursive0.diag
- TypeCobol.Analysis.Test/BasicCfgInstrs/PerformIdentity.diag
- TypeCobol.Analysis.Test/BasicCfgInstrs/PerformProc1Recursive0.diag
- TypeCobol.Analysis.Test/BasicCfgInstrs/PerformProc2Recursive0.diag
- TypeCobol.Analysis.Test/BasicCfgInstrs/PerformProc3Recursive0.diag
- TypeCobol.Analysis.Test/BasicCfgInstrs/PerformProc4Recursive0.diag
- TypeCobol.Analysis.Test/BasicCfgInstrs/PerformProcIterativeAfterRecursive0.diag
- TypeCobol.Analysis.Test/BasicCfgInstrs/PerformProcIterativeAfterRecursive1.diag
- TypeCobol.Analysis.Test/BasicCfgInstrs/PerformProcIterativeAfterRecursive2.diag
- TypeCobol.Analysis.Test/BasicCfgInstrs/PerformProcIterativeRecursive0.diag
- TypeCobol.Analysis.Test/BasicCfgInstrs/SG102A.diag
- TypeCobol.Analysis/Cfg/ControlFlowGraphBuilder.BasicBlockForNodeGroup.cs
- TypeCobol.Analysis/Cfg/ControlFlowGraphBuilder.cs
- TypeCobol.Analysis/Graph/BasicBlock.cs
- TypeCobol.Analysis/Graph/ControlFlowGraph.cs
- TypeCobol.Analysis/Resource.Designer.cs
- TypeCobol.Analysis/Resource.resx
- TypeCobol/Compiler/Directives/TypeCobolOptions.cs
- TypeCobol/Tools/Options-Config/TypeCobolConfiguration.cs
This is a complement to #2099.
As the PERFORM recursivity check will be moved to our private code-quality analyzer, this PR removes the previous implementation from the parser.
> WI #2039 Remove PERFORM recursivity check from CFG

- TypeCobol.Test/Parser/Programs/Cobol85/NoConfSectionInNestedPrg.rdz.cbl
- TypeCobol.Test/Parser/Programs/Cobol85/NoConfSectionInNestedPrg.rdzMix.txt
- TypeCobol/Compiler/Diagnostics/CrossChecker.cs
**What have been done**
A diagnostic is added to report an error in case presence of a CONFIGURATION SECTION in a nested program.
A test case is also adedd.
> 1874 new diag conf section in nested program

- TypeCobol.Test/Parser/CodeElements/IFInvalidConditions.cbl
- TypeCobol.Test/Parser/CodeElements/IFInvalidConditions.txt
- TypeCobol/Compiler/Parser/CodeElementBuilder/CobolWordsBuilder.cs
Fixes #2163.
Both syntax are invalid according to the IBM compiler, so our parser should reject them as well.
The exception has been fixed by checking for null and returning a null `SymbolReference`. Although not checked in every usages the property storing the SymbolReference is already marked as `[CanBeNull]`.
> WI #2163 Fix NullReferenceException on invalid condition expressions

- TypeCobol.Test/Parser/CodeElements/IF.cbl
- TypeCobol.Test/Parser/CodeElements/IF.txt
- TypeCobol/AntlrGrammar/CobolExpressions.g4
- TypeCobol/Compiler/Parser/CodeElementBuilder/CobolExpressionsBuilder.cs
Fixes #2165.
IBM compiler allows parentheses around identifiers in all condition types, our parser lacked this feature only in class conditions.
> WI #2165 Allow parentheses around identifers in conditions

- TypeCobol.Analysis/Dfa/DefaultDataFlowGraphBuilder.cs
- TypeCobol.Analysis/Dfa/ValueOrigin.cs
- TypeCobol/Compiler/Diagnostics/CrossChecker.cs
This is not a fix for #1774 but a safety. The real bug is located in our private analyzer which did not check properly for null values coming from the 2 dictionaries.
> WI #1774 Protect against null values coming from StorageArea[Reads/Writes]Symbol dictionaries

- CLI/src/DefaultCopies/SQLCA.cpy
Use SQLCA copy definition for system Z instead of series I.
> WI #2252 Use SQLCA definition for system Z

- TypeCobol.Test/Parser/Copies/ContainingCode.rdz-Nodes.txt
- TypeCobol.Test/Parser/Copies/ContainingCode.rdz.cpy
- TypeCobol/Compiler/CompilationUnit.cs
- TypeCobol/Compiler/Parser/CopyParsing/ProgramSkeleton.cs
> WI #2294 Avoid exception when parsing a copy containing statements

- Codegen/test/TestTypeCobolCodegen.cs
- TypeCobol.Analysis.Test/CfgDfaBuildingTests.cs
- TypeCobol.Test/Parser/CodeElements/EXEC.txt
- TypeCobol.Test/Parser/Preprocessor/TestCompilerDirectiveBuilder.cs
- TypeCobol.Test/Parser/Programs/Cobol85/ExecSql/CopyWithExecSqlAndData1.cpy
- TypeCobol.Test/Parser/Programs/Cobol85/ExecSql/CopyWithExecSqlAndData2.cpy
- TypeCobol.Test/Parser/Programs/Cobol85/ExecSql/CopyWithExecSqlOnly.cpy
- TypeCobol.Test/Parser/Programs/Cobol85/ExecSql/ExecSqlInDataDivision.rdz.cbl
- TypeCobol.Test/Parser/Programs/Cobol85/ExecSql/ExecSqlInDataDivision.rdzMix.txt
- TypeCobol.Test/Parser/Programs/TypeCobol/NodeBuilder-UnexpectedChild.rdz-Nodes.txt
- TypeCobol.Test/Parser/Scanner/ResultFiles/ExecStatement.txt
- TypeCobol.Test/Parser/Scanner/TestRealPrograms.cs
- TypeCobol.Test/Utils/Comparator.cs
- TypeCobol/Common.props
- TypeCobol/Compiler/Directives/TypeCobolOptions.cs
- TypeCobol/Compiler/Scanner/Scanner.cs
Fixes #2289.
- new option `EnableSqlParsing`, default to `false`
- removal of `SQl_PARSING` compilation constant which is not required anymore
When using `FolderTester`, tests located in a directory containing the string "SQL" are automatically parsed using sql parsing.
> WI #2289 Add optional SQL parsing

- TypeCobol/Compiler/CodeModel/SymbolTable.cs
- TypeCobol/Compiler/CupParser/NodeBuilder/ProgramClassBuilder.cs
- TypeCobol/Logging/LoggingSystemExtensions.cs
Instead of changing the `ProgramClassBuilder` workflow, I'd like to try this solution which ensure a `Paragraph` won't be relocated as a child of a `Sentence`.
> WI #2185 Relocate only statements when new Sentence is created

- TypeCobol/Compiler/CupParser/NodeBuilder/ProgramClassBuilder.cs
- TypeCobol/Logging/LoggingSystemExtensions.cs
Temporary code for #2332.
As `SourceText` is used only in debug code itself (CreateDebugData / ProgramClassBuilder), this will also allow to get complete traces.
> WI #2332 Add Debug code for exception in CodeElement.SourceText

- TypeCobol/Compiler/CodeElements/Expressions/SyntaxValue.cs
- TypeCobol/Compiler/Parser/CodeElementBuilder/CobolCodeElementBuilder.cs
> WI #2339 Do not create invalid IntegerValue for MaxBlockSize of a file description

- TypeCobol.LanguageServer/Completion Factory/CompletionFactory.cs
- TypeCobol.LanguageServer/TypeCobolServer.cs
- TypeCobol/Compiler/CodeModel/SymbolTable.cs
- TypeCobol/Compiler/Nodes/Data.cs
Fixes #2347.
Also removes unwanted usages of `System.Linq.Expressions` as described in #2170.
> WI #2347 Check for null LevelNumbers in completion operations

- TypeCobol.Test/Parser/Incremental/TestIncrementalPipeline.cs
- TypeCobol.Test/Utils/FolderTester.cs
16 exclusions but will go back to 1 failing tests after fixing #2474 and #2476.
> WI #2457 Temporary exclude failing tests for ClearDocumentThenRewriteLineByLine

- TypeCobol.LanguageServer/JsonRPC/IRPCHandler.cs
- TypeCobol.LanguageServer/JsonRPC/JsonRPCServer.cs
- TypeCobol.LanguageServer/StdioHttp/IMessageHandler.cs
- TypeCobol.LanguageServer/TypeCobolCustomLanguageServer/TypeCobolCustomLanguageServer.cs
- TypeCobol.LanguageServer/TypeCobolServer.cs
- TypeCobol.LanguageServer/TypeCobolServerHost.cs
- TypeCobol.LanguageServer/Utilities/MessageActionWrapper.cs
- TypeCobol.LanguageServer/VsCodeProtocol/LanguageServer.cs
Fix #2482.
Add a new LSPProfiling object which is passed to all LSP methods that process a message.
LSPProfiling contains:
```C#
/// <summary>
/// Time waited in the queue in milliseconds.
/// </summary>
public long InQueueDuration { get; }
/// <summary>
/// Number of messages left to process
/// </summary>
public long NumberOfMessagesToProcess { get; }
```
DidSave method will return without doing anything if the message waited in the queue more than 2 seconds.
> WI #2482 did save only rescan whole document if LSP server don't lag

- TypeCobol/Compiler/CodeElements/Expressions/SyntaxValue.cs
Actually getting the value on a `EnumeratedValue ` might crash because `ValueNeedsCompilationContext`, `ValueNeedsSymbolicCharactersMap `and `ValueNeedsCharactersCountContext `are not defined.
As a result `ToString `on a `EnumeratedValue ` returns 'Illegal &lt;token&gt;'.
Enumerated value should logically always be the token text and depend on nothing.
> WI #2509 Fix crash when getting value on an EnumeratedValue

- TypeCobol/Compiler/Scanner/Scanner.cs
Looks like GitHub did not pick 1def38bef639e0a6307a4f0b77b73b256aff6e4a while PR #2537 was still active.
This resulted in a failed merge with erroneous code.
> WI #2527 Fix code after failed merge

- CLI/src/CLI.cs
- CLI/test/CLITest.cs
- CLI/test/ressources/replacingSyntaxOption/CLIArguments.txt
- CLI/test/ressources/replacingSyntaxOption_OnlyApplyCopySuffixing/CLIArguments.txt
- CLI/test/ressources/replacingSyntaxOption_OnlyApplyCopySuffixing/input/CPY.list
- CLI/test/ressources/replacingSyntaxOption_OnlyApplyCopySuffixing/input/YCONVEA.CPY
- CLI/test/ressources/replacingSyntaxOption_OnlyApplyCopySuffixing/input/replacingSyntaxPartial.rdz.tcbl
- CLI/test/ressources/replacingSyntaxOption_OnlyApplyCopySuffixing/output_expected/error.txt
- CLI/test/ressources/replacingSyntaxOption_OnlyRemoveFirst01Level/CLIArguments.txt
- CLI/test/ressources/replacingSyntaxOption_OnlyRemoveFirst01Level/input/CPY.list
- CLI/test/ressources/replacingSyntaxOption_OnlyRemoveFirst01Level/input/YCONVEA.CPY
- CLI/test/ressources/replacingSyntaxOption_OnlyRemoveFirst01Level/input/replacingSyntaxPartial.rdz.tcbl
- CLI/test/ressources/replacingSyntaxOption_OnlyRemoveFirst01Level/output_expected/error.txt
- Codegen/src/Actions/Remarks.cs
- Codegen/test/CodegenTestUtils.cs
- TypeCobol.LanguageServer/TypeCobolServer.cs
- TypeCobol.LanguageServer/TypeCobolServerHost.cs
- TypeCobol.LanguageServer/Workspace.cs
- TypeCobol.LanguageServer/WorkspaceProjectStore.cs
- TypeCobol/Compiler/CompilationDocumentCache.cs
- TypeCobol/Compiler/CupPreprocessor/CompilerDirectiveBuilder.cs
- TypeCobol/Compiler/Directives/CompilerDirective.cs
- TypeCobol/Compiler/Directives/TypeCobolOptions.cs
- TypeCobol/Compiler/Preprocessor/ImportedTokensDocument.cs
- TypeCobol/Compiler/Preprocessor/ReplacingTokensLinesIterator.cs
- TypeCobol/Compiler/Scanner/Scanner.cs
- TypeCobol/LanguageServices/CodeAnalysis/Statistics/StatsGenerator.cs
- TypeCobol/Tools/Options-Config/TypeCobolConfiguration.cs
Fixes #2538
a40fad3336132b7795dffb177b8cc7b6cad94b9f is incorrectly linked to #2358 instead of #2538. Sorry about that.
> WI #2538 Split EI-Legacy REPLACING syntax option over 2 separate options

- TypeCobol.LanguageServer/Completion Factory/CodeElementMatcher.cs
- TypeCobol.LanguageServer/Completion Factory/CompletionFactory.cs
- TypeCobol.LanguageServer/Completion Factory/CompletionFactoryHelpers.cs
- TypeCobol.LanguageServer/TypeCobolServer.cs
- TypeCobol/Compiler/Diagnostics/Cobol2002Checker.cs
- TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs
Fixes #2170.
No need to do anything on the `*QualifiedName*` properties as they are backed up by a field to avoid multiple computations.
> WI #2170 Remove multiple LINQ enumerations to optimize completion

- TypeCobol.Test/Parser/Programs/Cobol85/ReplaceWithMultipleRules.ProcessedTokens.txt
- TypeCobol.Test/Parser/Programs/Cobol85/ReplaceWithMultipleRules.rdz.cbl
- TypeCobol.Test/Utils/Comparators.cs
- TypeCobol/Compiler/Scanner/Token.cs
- TypeCobol/Compiler/Text/CobolChar.cs
WI #2477 Check for 'replace separator' around token to replace
'replace separator' can be around token to replace or there can be at the beginning and end of the replacement token.
New ICompilationResultFormatter/Comparisons : ProcessedTokens.
This allow to see the source code with replaced token applied.
> WI #2477 Check for 'replace separator' around token to replace

- TypeCobol/Compiler/Preprocessor/AbstractReplaceTokensLinesIterator.cs
- TypeCobol/Compiler/Preprocessor/AutoReplacePartialWordsTokensDocument.cs
- TypeCobol/Compiler/Preprocessor/ReplaceTokensLinesIterator.cs
- TypeCobol/Compiler/Preprocessor/ReplacingTokensLinesIterator.cs
WI #2218 Scan during Replace preserve original column and line
Temporary Virtual Line used to rescan replaced token:
- Always use the lineIndex of the original line
- The line preserve space characters before first token
- Keep the ColumnLayout of the original line
Rewrite AutoReplaceIterator with AbstractReplaceTokensLinesIterator.
> WI #2218 Preserve column and line while rescanning during a REPLACE

- TypeCobol.Test/Parser/Programs/Cobol85/ContinuationLine/ContinuationLine.Mix.txt
- TypeCobol.Test/Parser/Programs/Cobol85/ContinuationLine/ContinuationLine2.Mix.txt
- TypeCobol.Test/Parser/Programs/Cobol85/ContinuationLine/ContinuationLine4.Mix.txt
- TypeCobol.Test/Parser/Programs/Cobol85/ContinuationLine/ContinuationLine6.Mix.txt
- TypeCobol.Test/Parser/Programs/Cobol85/ContinuationLine/ContinuationLine8.Mix.txt
- TypeCobol/Compiler/Scanner/Scanner.cs
- TypeCobol/Compiler/Text/CobolTextLine.cs
- TypeCobol/Compiler/Text/ColumnsLayout.cs
WI #2357 Virtual line used by continuation line preserve original column of the first line
Fix column of diagnostics on continued lines.
Introduce new ColumnLayout CobolReferenceFormatWithoutComment which is like CobolReferenceFormat but with unlimited line length. 
This column layout should only be used by continuation line.
> WI #2357 Preserve original column of virtual concatenated line

- TypeCobol.LanguageServer/Workspace.cs
Fixes #2600
To reproduce the crash in a Cobol program: remove the . after IDENTIFICATION DIVISION
> WI #2600 Fix NullReferenceException in Workspace.CollectDataLayoutNodes

- TypeCobol/Compiler/CodeModel/SymbolTable.cs
> WI #2610 Fix REDEFINES target lookup

- TypeCobol.LanguageServer.Test/LSRTest.cs
- TypeCobol.LanguageServer.Test/LSRTests/ExecuteCommandRefactorAdjustFillers_BadLocation/input/ExecuteCommandRefactorAdjustFillers_BadLocation.tlsp
- TypeCobol.LanguageServer.Test/LSRTests/ExecuteCommandRefactorAdjustFillers_BadLocation/output_expected/ExecuteCommandRefactorAdjustFillers_BadLocation.rlsp
- TypeCobol.LanguageServer/Commands/AdjustFillers.cs
- TypeCobol/Compiler/Nodes/Node.cs
Fixes #2647
Also ignore INDEX among children to avoid a crash when retrieving the CodeElement (which is null for an Index node)
> 2647 adjust filler may insert filler at bad location

- Codegen/test/CodegenTestUtils.cs
- TypeCobol.Analysis.Test/CfgDfaDominatorTests.cs
- TypeCobol.Analysis.Test/CfgTestUtils.cs
- TypeCobol.Analysis.Test/DfaCallPgmReport.cs
- TypeCobol.Test/GrammarTest.cs
- TypeCobol.Test/Misc/CopyTokenProperties.cpy
- TypeCobol.Test/Misc/TestExpressions.cs
- TypeCobol.Test/Misc/TestTokenProperties.cs
- TypeCobol.Test/Misc/TokenProperties-SourceText.txt
- TypeCobol.Test/Misc/TokenProperties.cbl
- TypeCobol.Test/Parser/Preprocessor/PreprocessorUtils.cs
- TypeCobol.Test/Parser/Scanner/ScannerUtils.cs
- TypeCobol.Test/Report/ReportTestHelper.cs
- TypeCobol.Test/TestCollection.cs
- TypeCobol.Test/TestUtils.cs
- TypeCobol.Test/Utils/ParserUtils.cs
- TypeCobol/Compiler/AntlrUtils/TokensLinesTokenSource.cs
Fixes #2599.
This is a simple fix for the index out of range error happening when evaluating the `SourceText` property.
As `MissingToken` instances don't refer to actual tokens found in text lines, the `Substring` operation to compute source text will always fail for them.
> WI #2599 Fix SourceText property for missing tokens

- TypeCobol.LanguageServer/Workspace.cs
- TypeCobol.LanguageServer/WorkspaceProjectStore.cs
Fixes #2664
- Keep names of all opened `WorkspaceProject` instances
- Remove useless `TryAdd` call when creating neww `WorkspaceProject`
> WI #2664 Ignore change notifications for closed projects

- TypeCobol.LanguageServer/TypeCobolServerHost.cs
- TypeCobol.LanguageServer/TypeCobolServerLogger.cs
- TypeCobol.LanguageServer/VsCodeProtocol/LanguageServer.cs
- TypeCobol.LanguageServer/VsCodeProtocol/Telemetry Notification/TelemetryEvent.cs
- TypeCobol.LanguageServer/VsCodeProtocol/Telemetry Notification/TelemetryNotification.cs
Fixes #2670
No new LSP tests:
- since `telemetry/event` is not tied to any document, I suspect LSR will drop the message
- the send happens on the logger thread so the message order is not guaranteed
I manually tested on our private client and the event is correctly sent and received.
> WI #2670 Use telemetry/event to send server exceptions to client

- TypeCobol.LanguageServer/VsCodeProtocol/Telemetry Notification/TelemetryEvent.cs
Mini-fix to use camel-case in `TelemetryEvent` object.
> WI #2668 Fix TelemetryEvent fields case to match JSON-style

- TypeCobol/Compiler/CompilationUnit.cs
- TypeCobol/Compiler/CupParser/NodeBuilder/ProgramClassBuilder.cs
- TypeCobol/Compiler/IncrementalChangesHistory.cs
- TypeCobol/Compiler/Parser/ProgramClassParserStep.cs
- TypeCobol/Logging/LoggingSystemExtensions.cs
> WI #2707 Avoid full source dump, keep code for future uses

- TypeCobol.Test/Parser/Incremental/BasicEdits/AddEmptyLineInTheMiddleThenRemove/DebugLinesWithDebugging.0.Nodes.txt
- TypeCobol.Test/Parser/Incremental/BasicEdits/AddEmptyLineInTheMiddleThenRemove/DebugLinesWithDebugging.1.Nodes.txt
- TypeCobol.Test/Parser/Incremental/BasicEdits/AddEmptyLineInTheMiddleThenRemove/DebugLinesWithDebugging.Nodes.txt
- TypeCobol.Test/Parser/Programs/Cobol85/DebugLinesWithDebugging.Nodes.txt
- TypeCobol/Compiler/Diagnostics/CodeElementCheckers.cs
- TypeCobol/Compiler/Diagnostics/CrossChecker.cs
- TypeCobol/Compiler/Directives/TypeCobolOptions.cs
- TypeCobol/Compiler/Parser/CodeElementBuilder/CobolCodeElementBuilder.cs
- TypeCobol/Tools/Options-Config/TypeCobolConfiguration.cs
Fixes #2731
Two changes in this PR:
- WI #2731 Add option for checking debug mix in CodeElement
- a new option is available to control the severity, and possibly disable, the check of CodeElements mixing debug and non-debug lines
- WI #2731 Remove option to check END PROGRAM
- remove the `diag.cep` option as the performed checks always resolve to an error on IBM compiler
Note that the second change is breaking so I am thonking of creating a v2.8.0 to release this.
> WI #2731 Add option for mixed debug check, remove option for END PROGRAM

- TypeCobol.LanguageServer.Test/RefactoringTests/InsertVariableDisplay/ExecSql/InsertAfterExecSql.cbl
- TypeCobol.LanguageServer.Test/RefactoringTests/InsertVariableDisplay/ExecSql/InsertBeforeExecSql.cbl
- TypeCobol.LanguageServer/Commands/InsertVariableDisplay/InsertVariableDisplayRefactoringProcessor.cs
> WI #2776 In InsertVariableDisplay always consider EXEC nodes as a whole to avoid insert code inside them
